### ISSUE TITLE
Save tutorials in a database

### ISSUE THREAD

**Issue by vanxdium** [Scratch-Tutorials/website#2]
For multiple reasons, saving our tutorials in a database could be easier for us. It would be easier for us to moderate them and for ppl to propose them. Also, it would make our repository cleaner than putting each tutorials into a specific file in a tiny directory.

**Comment by ha2pex** [comment]
Hey, I see what you mean about. I often think about that solution, but I don't feel comfortable with databases.

Plus it would cause several issues such as the authentication, the database available space *as we will us a free plan*, ect. I temporarily close this issue as a wontfix but I'll think about it.
